# General
dataroot: Task2202_picai_OnlyTumor
yh_run_model: Train
dataset_mode: nnUNetWPriors
TrainConfig: PRIORSConfig
plan: nnUNetPlansv2.1_plans_3D.pkl
Deterministic: True

# model setting
encoder: UNETR
imageSize: [96,96,96]
region: [None]
patchSize: 16
num_layers: 12
mlp_dim: 3072
num_heads: 12
hidden_size: 768
norm_name: instance

#trainer
num_training_steps_per_epoch: 50
num_validation_steps_per_epoch: 10
validate_min_epoch: 1
gpu_ids: 0
fold: 0
input_nc: 3
output_nc: 1
epochs: 50
amsgrad: True
loss_option: DiceCELoss
lr: 1e-4
postprocessing: Picai_Postprocessing
sigmoid: True
batchSize: 1
Val_batchSize: 1
VAL_AMP: True
debug: False

# training schedule
sched: warmup_cosine
warmup_epochs: 10
dr: 0.4

#Optimizer
weight_decay: 1e-5
opt: adamw 

loadsplit: nnUNet/splits.json

# wandb
project: LocalTrials
enable_wandb: True
nameRun: ${TrainConfig}_UNETR_trial1
name: ${TrainConfig}_UNETR_trial1

