# General
dataroot: Task2202_picai_OnlyTumor
yh_run_model: Train
dataset_mode: nnUNetWPriors
TrainConfig: PRIORSConfig
plan: nnUNetPlansv2.1_plans_3D.pkl
Deterministic: True
loadsplit: nnUNet/splits.json


# model setting
encoder: UNETR_MAE
enc_arch: ViTBackbone
dec_arch: UNETR_decoder
imageSize: [96,96,96]
region: [None]
patchSize: 16
feature_size: 32
num_layers: 12
mlp_dim: 3072
num_heads: 12
hidden_size: 768
norm_name: instance
drop_path_rate: 0.1
prompt_embed_dim: ${hidden_size} #value of prompt embedding and encoder output
mask_in_chans: 16 #value for embedding mask
input_prior: [0] #value to indicate the priors to be used (index of prior matrix) 


#trainer 
num_training_steps_per_epoch: 25
num_validation_steps_per_epoch: 15
validate_min_epoch: 1
gpu_ids: 0
fold: 0
input_nc: 3
output_nc: 1
epochs: 10
amsgrad: True
loss_option: DiceCELoss
lr: 1e-4 #1e-3
postprocessing: Picai_Postprocessing
sigmoid: True
batchSize: 2
Val_batchSize: 1
VAL_AMP: False
debug: False


# training schedule
sched: cosine_anneal
warmup_epochs: 10
dr: 0.4 #decay_rate

#Optimizer
weight_decay: 1e-5 # 0.05
opt: adamw 
opt_betas: [0.9,0.95]



# wandb
project: LocalTrials
enable_wandb: False
nameRun: ${TrainConfig}_e${epochs}
name: ${TrainConfig}_e${epochs}

