wandb_version: 1

.:
  desc: null
  value: 0
Deterministic:
  desc: null
  value: true
Earlyfusion:
  desc: null
  value: Concatenation
PatchNCELoss:
  desc: null
  value: false
SupContrast:
  desc: null
  value: false
TrainConfig:
  desc: null
  value: BaseConfig
VAL_AMP:
  desc: null
  value: true
Val_batchSize:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1674817616.605093
    t:
      1:
      - 1
      - 10
      - 11
      - 41
      - 48
      - 49
      - 55
      - 63
      2:
      - 1
      - 5
      - 10
      - 11
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.13.9
      6: 4.25.1
      8:
      - 1
      - 5
batchSize:
  desc: null
  value: 2
checkpoints_dir:
  desc: null
  value: dataLowRegime
conv_kernel_sizes:
  desc: null
  value:
  - - 3
    - 3
    - 3
  - - 3
    - 3
    - 3
  - - 3
    - 3
    - 3
  - - 3
    - 3
    - 3
  - - 3
    - 3
    - 3
  - - 3
    - 3
    - 3
dataroot:
  desc: null
  value: Task002_Hektor
dataset_mode:
  desc: null
  value: nnUNet
device:
  desc: null
  value: cuda
display_id:
  desc: null
  value: 1
dist_on_itp:
  desc: null
  value: false
dist_url:
  desc: null
  value: env://
dropout_rate:
  desc: null
  value: 0.1
enable_wandb:
  desc: null
  value: true
encoder:
  desc: null
  value: Unet
epochs:
  desc: null
  value: 10
expr_dir:
  desc: null
  value: ./checkpoints/Task002_Hektor/dataLowRegime/Unet/UnetF0
filters_Encoder:
  desc: null
  value:
  - 16
  - 32
  - 64
  - 128
fold:
  desc: null
  value: 0
gpu_ids:
  desc: null
  value:
  - 0
hidden_size:
  desc: null
  value: 768
imageSize:
  desc: null
  value:
  - 128
  - 128
  - 128
input_nc:
  desc: null
  value: 2
isTrain:
  desc: null
  value: true
lambdaCNN:
  desc: null
  value: 0.1
lambdaViT:
  desc: null
  value: 0.01
loadsplit:
  desc: null
  value: LowDataRegime/Hektor_5fold_V2.pkl
local_rank:
  desc: null
  value: -1
log_writer:
  desc: null
  value: <util.loggings.TensorboardLogger object at 0x7f972e69eee0>
lr:
  desc: null
  value: 0.001
mlp_dim:
  desc: null
  value: 3072
n_splits:
  desc: null
  value: 5
name:
  desc: null
  value: UnetF0
norm_name:
  desc: null
  value: instance
num_heads:
  desc: null
  value: 12
num_layers:
  desc: null
  value: 12
num_pool_per_axis:
  desc: null
  value:
  - 5
  - 5
  - 5
out_dir:
  desc: null
  value: ./Output/Task002_Hektor/dataLowRegime/Unet/UnetF0
output_dir:
  desc: null
  value: dataLowRegime
output_nc:
  desc: null
  value: 1
patchSize:
  desc: null
  value: 1
plan:
  desc: null
  value: nnUNetPlansv2.1_plans_3D.pkl
planning_stage:
  desc: null
  value: nnUNetData_plans_v2.1_stage0
pool_op_kernel_sizes:
  desc: null
  value:
  - - 2
    - 2
    - 2
  - - 2
    - 2
    - 2
  - - 2
    - 2
    - 2
  - - 2
    - 2
    - 2
  - - 2
    - 2
    - 2
pos_embed:
  desc: null
  value: perceptron
pretrained:
  desc: null
  value: null
pretrained2d:
  desc: null
  value: false
project:
  desc: null
  value: MIAM
region:
  desc: null
  value:
  - None
res_block:
  desc: null
  value: true
seed:
  desc: null
  value: 12345
spatial_dims:
  desc: null
  value: 3
stage:
  desc: null
  value: 0
val_interval:
  desc: null
  value: 1
wandb_ckpt:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.05
world_size:
  desc: null
  value: 1
yh_run_model:
  desc: null
  value: Train
